---
framework: mocha
preRun:
     command:
        - npx rust-app rustup-init
        - source "$HOME/.cargo/env"
        - yarn --frozen-lockfilearn
        - yarn build-native-release
preMerge:
  env:
      NODE_ENV: test
  pattern: 
    - "packages/core/core/test/*.test.js"
postMerge:
  env:
      NODE_ENV: test
  pattern: 
    - "packages/core/core/test/*.test.js"
postRun:
     command:
        - echo "hello"
configFile: ".mocharc.json"
version: 1.0.0
